services:
  auth-service:
    build: ./auth-service
    container_name: healink-auth
    ports:
      - "3001:3001"
    env_file: .env
    volumes:
      - ./shared-wallet:/app/shared-wallet
    deploy:
      resources:
        limits:
          memory: 200M

  admin-service:
    build: ./admin-service
    container_name: healink-admin
    ports:
      - "3002:3002"
    env_file: .env
    volumes:
      - ./shared-wallet:/app/shared-wallet
    deploy:
      resources:
        limits:
          memory: 200M

  user-service:
    build: ./user-service
    container_name: healink-user
    ports:
      - "3003:3003"
    env_file: .env
    volumes:
      - ./shared-wallet:/app/shared-wallet
    deploy:
      resources:
        limits:
          memory: 200M

  sos-core-service:
    build: ./sos-core-service
    container_name: healink-sos-core
    ports:
      - "3004:3004"
    env_file: .env
    volumes:
      - ./shared-wallet:/app/shared-wallet
    deploy:
      resources:
        limits:
          memory: 200M