replicaCount: 1
image:
  pullPolicy: Never

services:
  admin:
    port: 3002
    image: docker.io/library/healink-admin:latest
  auth:
    port: 3001
    image: docker.io/library/healink-auth:latest
  user:
    port: 3003
    image: docker.io/library/healink-user:latest
  sos:
    port: 3004
    image: docker.io/library/healink-sos:latest