replicaCount: 1
image:
  pullPolicy: IfNotPresent

services:
  admin:
    port: 3002
    image: healink-admin
  auth:
    port: 3001
    image: healink-auth
  user:
    port: 3003
    image: healink-user
  sos:
    port: 3004
    image: healink-sos