{{- range $name, $config := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-service
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $config.image }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:                             # Crucial para el Wallet de Oracle
            - name: TNS_ADMIN
              value: "/app/shared-wallet"
          envFrom:                         # Inyecta tu .env desde el Secret
            - secretRef:
                name: healink-secrets
          ports:
            - containerPort: {{ $config.port }}
          resources:
            limits:
              memory: "180Mi"              # Ajustado para tu servidor de 1GB
            requests:
              memory: "100Mi"
          volumeMounts:
            - name: wallet-volume
              mountPath: /app/shared-wallet
      volumes:
        - name: wallet-volume
          hostPath:
            path: /home/ubuntu/HealinkSOS-API/shared-wallet
{{- end }}